/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.calculator.Calculator;

public class App {
    Calculator calculator = new Calculator();

    public String getGreeting() {
        return "Hello World!";
    }

    public Calculator getCalculator() {
        return calculator;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
